In [21]:
import random
import math
import numpy as np

# m개의 train samples, n개의 test samples
m, n = 10000, 1000

# sample 생성 함수 정의
def generate_sample(num):
    x, y = [], []
    for i in range(num):
        degree_value = random.uniform(0, 360)
        sine_value = math.sin(math.radians(degree_value))
        x.append(degree_value)
        if sine_value > 0:
            y.append(1)
        else:
            y.append(0)
    x = np.array([x])
    y = np.array([y])
    
    return x, y 

# train samples 와 test samples 생성
x_train, y_train = generate_sample(m)
x_test, y_test = generate_sample(n)

print(x_train)
print(y_train)

[[105.54651251 200.78795184  73.35778332 ... 335.88511057  97.28559089
   68.61076916]]
[[1 0 1 ... 0 1 1]]


In [22]:
# W, b 를 초기화
b1, b2 = 0.1, -0.05
W1, W2 = np.array([[0.001]]), np.array([[2.0]])

def sigmoid(x):
    sig = 1 / (1 + np.exp(-x))
    return sig

# k번 업데이트
k = 5000

# alpha 값 지정 후 W, b 업데이트
alpha = 0.001
for i in range(int(k/500)):
    for j in range(int(k/10)):
        
        # forward
        Z1 = np.dot(W1.T, x_train) + b1
        A1 = sigmoid(Z1)
        Z2 = np.dot(W2.T, A1) + b2
        A2 = sigmoid(Z2)
        
        # backpropagation
        dZ2 = A2 - y_train 
        dW2 = np.dot(dZ2, A1.T) / m 
        db2 = np.sum(dZ2, axis=1, keepdims=True) / m
        dZ1 = np.dot(W2.T, dZ2) * (A1 * (1 - A1))
        dW1 = np.dot(dZ1, x_train.T) / m
        db1 = np.sum(dZ1, axis=1, keepdims=True) / m

        # W,b 업데이트
        W1 -= alpha * dW1
        b1 -= alpha * db1
        W2 -= alpha * dW2
        b2 -= alpha * db2
        
    # 500번마다 업데이트된 W,b 출력
    print(f'{i+1}번째 W1:{W1}, W2:{W2}, b1:{b1}, b2:{b2}')
    
print(x_train[:, :3])
print(Z1[:, :3])
print(A1[:, :3])
print(Z2[:, :3])
print(A2[:, :3])


1번째 W1:[[-0.01197007]], W2:[[2.01810181]], b1:[[0.12163559]], b2:[[-0.08633925]]
2번째 W1:[[-0.01186554]], W2:[[2.03724596]], b1:[[0.14430636]], b2:[[-0.12045084]]
3번째 W1:[[-0.01178064]], W2:[[2.0569626]], b1:[[0.16763844]], b2:[[-0.15195998]]
4번째 W1:[[-0.01171341]], W2:[[2.07721824]], b1:[[0.19159348]], b2:[[-0.18116622]]
5번째 W1:[[-0.0116621]], W2:[[2.09798121]], b1:[[0.21613485]], b2:[[-0.20833731]]
6번째 W1:[[-0.01162514]], W2:[[2.11922165]], b1:[[0.24122763]], b2:[[-0.23371227]]
7번째 W1:[[-0.01160114]], W2:[[2.14091142]], b1:[[0.26683846]], b2:[[-0.25750433]]
8번째 W1:[[-0.01158884]], W2:[[2.16302405]], b1:[[0.29293552]], b2:[[-0.27990355]]
9번째 W1:[[-0.01158715]], W2:[[2.18553459]], b1:[[0.31948835]], b2:[[-0.30107923]]
10번째 W1:[[-0.01159505]], W2:[[2.20841956]], b1:[[0.34646779]], b2:[[-0.32118211]]
[[105.54651251 200.78795184  73.35778332]]
[[-0.87740114 -1.98172812 -0.50417199]]
[[0.29371661 0.12113474 0.37656074]]
[[ 0.32749308 -0.05363215  0.51044385]]
[[0.58114928 0.48659518 0.62491

In [23]:
# cross-entropy loss 함수 정의
def cost_func(W1, W2, x, y, num):
    Z1 = np.dot(W1.T, x) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2.T, A1) + b2
    A2 = sigmoid(Z2)
    J = -1 * (np.dot(y, np.log(A2).T) + np.dot((1-y), np.log(1-A2).T)) / num
    return J
# train cost와 test cost 출력
print('train cost:', cost_func(W1, W2, x_train, y_train, m))
print('test cost:', cost_func(W1, W2, x_test, y_test, n))

train cost: [[0.56082391]]
test cost: [[0.56432636]]


In [24]:
# train samples에 대한 accuracy와 test samples에 대한 accuracy 출력
def accuracy(W1, W2, x, y):
    Z1 = np.dot(W1.T, x) + b1
    A1 = sigmoid(Z1)
    Z2 = np.dot(W2.T, A1) + b2
    A2 = sigmoid(Z2)
    A2[A2 > 0.5] = 1
    A2[A2 < 0.5] = 0
    accuracy = np.mean(np.equal(y, A2)) * 100
    return accuracy

print('train_accuracy:', accuracy(W1, W2, x_train, y_train))
print('test_accuracy:', accuracy(W1, W2, x_test, y_test))


train_accuracy: 99.37
test_accuracy: 99.2
